---
name: sd-generate
extra-source-files: [ ]
dependencies:
  - base
  - bytestring
  - call-alloy
  - call-plantuml
  - containers
  - ilist
  - mtl
  - diagrams-lib
  - diagrams-svg
  - SVGFonts
  - extra
  - svg-builder
  - QuickCheck
  - string-interpolate
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Datatype
    - Example
    - CounterExample
    - Checkers
    - Instance
    - Layout
    - Generate
    - AlloyDiagrams
    - PlantUMLDiagrams
  ghc-options:
    - -Wall
    - -Werror
executables:
  sampling:
    main: sampling.hs
    source-dirs: app
    dependencies:
      - sd-generate
      - pretty-simple
  draw:
    main: draw.hs
    source-dirs: app
    dependencies:
      - sd-generate
  drawing:
    main: drawing.hs
    source-dirs: app
    dependencies:
      - sd-generate
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - sd-generate
  transformAlloy:
    main: transformAlloy.hs
    source-dirs: app
    dependencies:
      - sd-generate
  transformPlantUML:
    main: transformPlantUML.hs
    source-dirs: app
    dependencies:
      - sd-generate
tests:
  sd-generate-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sd-generate
      - hspec
