---
name: ba-sergei-lestsenski
extra-source-files: [ ]
dependencies:
  - base
  - bifunctors
  - generic-functor
  - bytestring
  - call-alloy
  - call-plantuml
  - containers
  - ilist
  - mtl
  - diagrams-lib
  - diagrams-svg
  - SVGFonts
  - extra
  - svg-builder
  - QuickCheck
  - string-interpolate
  - hashable
  - pretty-simple
  - lens
  - output-monad
  - file-embed
  - filepath
  - MonadRandom
  - monad-loops
  - modelling-tasks
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Modelling.StateDiagram.Alloy
    - Modelling.StateDiagram.Config
    - Modelling.StateDiagram.Datatype
    - Modelling.StateDiagram.Datatype.ClassInstances
    - Modelling.StateDiagram.Example
    - Modelling.StateDiagram.CounterExample
    - Modelling.StateDiagram.Checkers
    - Modelling.StateDiagram.Instance
    - Modelling.StateDiagram.Layout
    - Modelling.StateDiagram.Generate
    - Modelling.StateDiagram.Flatten
    - Modelling.StateDiagram.AlloyDiagrams
    - Modelling.StateDiagram.PlantUMLDiagrams
    - Modelling.StateDiagram.Style
    - Modelling.StateDiagram.Simulate
    - Modelling.StateDiagram.EnumArrows
  ghc-options:
    - -Wall
    - -Werror
executables:
  enumeratedArrowsDemo:
    main: enumeratedArrowsDemo.hs
    source-dirs:
      - app
      - .
      - app/common
    dependencies:
      - ba-sergei-lestsenski
      - output-monad
      - transformers
      - time
      - directory
    other-modules:
      - Common
    ghc-options:
      - -Wall
      - -Werror
  sampling:
    main: sampling.hs
    source-dirs: app
    dependencies:
      - ba-sergei-lestsenski
      - pretty-simple
    ghc-options:
      - -Wall
      - -Werror
  draw:
    main: draw.hs
    source-dirs: app
    dependencies:
      - ba-sergei-lestsenski
    ghc-options:
      - -Wall
      - -Werror
  drawing:
    main: drawing.hs
    source-dirs: app
    dependencies:
      - ba-sergei-lestsenski
    ghc-options:
      - -Wall
      - -Werror
  transformAlloy:
    main: transformAlloy.hs
    source-dirs: app
    dependencies:
      - ba-sergei-lestsenski
    ghc-options:
      - -Wall
      - -Werror
  transformPlantUML:
    main: transformPlantUML.hs
    source-dirs: app
    dependencies:
      - ba-sergei-lestsenski
    ghc-options:
      - -Wall
      - -Werror
tests:
  ba-sergei-lestsenski-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-sergei-lestsenski
      - modelling-tasks
      - output-monad
      - file-embed
      - call-alloy
      - directory
      - filepath
      - hspec
      - transformers
