---
resolver: lts-20.18
packages:
  - .
extra-deps:
  - call-alloy-0.4.0.3
  - git: https://github.com/fmidue/output-monad.git
    commit: 4ca058f25d2d377454df1b4ffb0dcda1753a2738
    subdirs:
      - output-monad
  - git: https://github.com/fmidue/modelling-tasks.git
    commit: 233281ae07b07f8679159218b087d6ba98dfd4d6
  - call-plantuml-0.0.1.3
  - latex-svg-image-0.2
  - hgal-2.0.0.3
  - diagrams-graphviz-1.4.1.1
  - random-shuffle-0.0.4
allow-newer: true
