---
resolver: lts-23.28
packages:
  - .
extra-deps:
  - call-alloy-0.6.0.2
  - git: https://github.com/fmidue/output-blocks.git
    commit: be840655231dd5118ee66e28de3343628882dce3
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/modelling-tasks.git
    commit: 9eac7889fbc436158cf39f4f962eda6263055264
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: 8ea4feae0cd9c184ae4127e59233f5e8f1b22717
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - git: https://git.uni-due.de/fmi/autotool-dev
    commit: bdd8e54b6c0480bb12bbc34f72c6f1247469f3b7
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util
  - call-plantuml-0.0.1.3
  - latex-svg-image-0.2
  - hgal-2.0.0.3
  - diagrams-graphviz-1.4.1.1
  - random-shuffle-0.0.4
allow-newer: true
