---
resolver: lts-20.18
packages:
  - .
extra-deps:
  - call-alloy-0.4.0.3
  - git: https://github.com/fmidue/output-monad.git
    commit: 4ca058f25d2d377454df1b4ffb0dcda1753a2738
    subdirs:
      - output-monad
  - git: https://github.com/fmidue/modelling-tasks.git
    commit: f047bce8f2d1641b4161d5f25ebb063821340efa
  - call-plantuml-0.0.1.2
  - latex-svg-image-0.2
  - hgal-2.0.0.3
  - diagrams-graphviz-1.4.1.1
  - ilist-0.4.0.1
  - random-shuffle-0.0.4
allow-newer: true
